### ISSUE TITLE
Issue running make

### ISSUE THREAD

**Issue by jeffreydpayne** [jniedrauer/logs-to-elastic#1]
I get the following issues running make...

$ make build
go build -v -o build/cloudwatch internal/app/cloudwatch/main.go
internal/app/cloudwatch/main.go:26:2: cannot find package "github.com/aws/aws-lambda-go/lambda" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/aws/aws-lambda-go/lambda (from $GOROOT)
	/Users/jeffreydpayne/go/src/github.com/aws/aws-lambda-go/lambda (from $GOPATH)
internal/app/cloudwatch/main.go:23:2: cannot find package "github.com/jniedrauer/logs-to-elastic/internal/pkg/handlers" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/jniedrauer/logs-to-elastic/internal/pkg/handlers (from $GOROOT)
	/Users/jeffreydpayne/go/src/github.com/jniedrauer/logs-to-elastic/internal/pkg/handlers (from $GOPATH)
internal/app/cloudwatch/main.go:24:2: cannot find package "github.com/jniedrauer/logs-to-elastic/internal/pkg/logging" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/jniedrauer/logs-to-elastic/internal/pkg/logging (from $GOROOT)
	/Users/jeffreydpayne/go/src/github.com/jniedrauer/logs-to-elastic/internal/pkg/logging (from $GOPATH)
make: *** [build/cloudwatch] Error 1

Probably just need to add a few "go get" commands to the make file

**Comment by jniedrauer** [comment]
I added documentation. The go dependency management tool `dep` is required for build.

EDIT: Huh, actually the order of dependencies for the build target was wrong. It should have said it was missing dep. Fixed.
